//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.reader;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class Pref_
    extends SharedPreferencesHelper
{

    private Context context_;

    public Pref_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_Pref"), 0));
        this.context_ = context;
    }

    public Pref_.PrefEditor_ edit() {
        return new Pref_.PrefEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public IntPrefField font() {
        return intField("font", 25);
    }

    public IntPrefField progress() {
        return intField("progress", 0);
    }

    public final static class PrefEditor_
        extends EditorHelper<Pref_.PrefEditor_>
    {


        PrefEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<Pref_.PrefEditor_> font() {
            return intField("font");
        }

        public IntPrefEditorField<Pref_.PrefEditor_> progress() {
            return intField("progress");
        }

    }

}
