//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.reader.engine;

import android.content.Context;

public final class BookEngine_
    extends BookEngine
{

    private Context context_;

    private BookEngine_(Context context) {
        context_ = context;
        init_();
    }

    public static BookEngine_ getInstance_(Context context) {
        return new BookEngine_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
