//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.abase.core;

import android.content.Context;

public final class AbaseHttp_
    extends AbaseHttp
{

    private Context context_;

    private AbaseHttp_(Context context) {
        context_ = context;
        init_();
    }

    public static AbaseHttp_ getInstance_(Context context) {
        return new AbaseHttp_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
