//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.abase.core;

import android.content.Context;

public final class AbaseDao_
    extends AbaseDao
{

    private Context context_;

    private AbaseDao_(Context context) {
        context_ = context;
        init_();
    }

    public static AbaseDao_ getInstance_(Context context) {
        return new AbaseDao_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
