//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.abase.core;

import android.content.Context;

public final class AbaseBitmap_
    extends AbaseBitmap
{

    private Context context_;

    private AbaseBitmap_(Context context) {
        context_ = context;
        init_();
    }

    public static AbaseBitmap_ getInstance_(Context context) {
        return new AbaseBitmap_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
