//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.jayqqaa12.abase.core;

import android.content.Context;

public final class ABitmap_
    extends ABitmap
{

    private Context context_;

    private ABitmap_(Context context) {
        context_ = context;
        init_();
    }

    public static ABitmap_ getInstance_(Context context) {
        return new ABitmap_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
