//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.jayqqaa12.abase.core;

import android.content.Context;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Abus_
    extends Abus
{

    private Context context_;
    private static Abus_ instance_;

    private Abus_(Context context) {
        context_ = context;
    }

    public static Abus_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new Abus_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
    }

}
