//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.jayqqaa12.abase.core;

import android.content.Context;

public final class AHttp_
    extends AHttp
{

    private Context context_;

    private AHttp_(Context context) {
        context_ = context;
        init_();
    }

    public static AHttp_ getInstance_(Context context) {
        return new AHttp_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
