//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.
//


package com.jayqqaa12.reader.ui.adapter;

import android.content.Context;
import com.jayqqaa12.reader.engine.BookEngine_;

public final class BookAdapter_
    extends BookAdapter
{

    private Context context_;

    private BookAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static BookAdapter_ getInstance_(Context context) {
        return new BookAdapter_(context);
    }

    private void init_() {
        context = context_;
        engine = BookEngine_.getInstance_(context_);
        init();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
